### ISSUE TITLE
Pleuston does not build: image not using full /config/ocean.js

### ISSUE THREAD

**Issue by theoturner** [oceanprotocol/pleuston#174]
```
./start-ocean.sh --latest
```
results in
```
pleuston_1_3ef9f14874d6 | Copying keeper-contracts artifacts...
pleuston_1_3ef9f14874d6 | 
pleuston_1_3ef9f14874d6 | Successfully copied keeper-contracts artifacts.
pleuston_1_3ef9f14874d6 | Creating an optimized production build...
pleuston_1_3ef9f14874d6 | Failed to compile.
pleuston_1_3ef9f14874d6 | 
pleuston_1_3ef9f14874d6 | ./config/ocean.js
pleuston_1_3ef9f14874d6 | SyntaxError: /pleuston/config/ocean.js: Unexpected token (12:0)
pleuston_1_3ef9f14874d6 | 
pleuston_1_3ef9f14874d6 |   10 |     aquariusHost: '',
pleuston_1_3ef9f14874d6 |   11 |     aquariusPort: 
pleuston_1_3ef9f14874d6 | > 12 | }
pleuston_1_3ef9f14874d6 |      | ^
pleuston_1_3ef9f14874d6 |   13 |
pleuston_1_3ef9f14874d6 | 
pleuston_1_3ef9f14874d6 | 
pleuston_1_3ef9f14874d6 | npm ERR! code ELIFECYCLE
pleuston_1_3ef9f14874d6 | npm ERR! errno 1
pleuston_1_3ef9f14874d6 | npm ERR! @oceanprotocol/pleuston@0.1.0 build: `node scripts/build.js`
pleuston_1_3ef9f14874d6 | npm ERR! Exit status 1
pleuston_1_3ef9f14874d6 | npm ERR! 
pleuston_1_3ef9f14874d6 | npm ERR! Failed at the @oceanprotocol/pleuston@0.1.0 build script.
pleuston_1_3ef9f14874d6 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
pleuston_1_3ef9f14874d6 | 
pleuston_1_3ef9f14874d6 | npm ERR! A complete log of this run can be found in:
pleuston_1_3ef9f14874d6 | npm ERR!     /root/.npm/_logs/2018-11-26T13_56_27_894Z-debug.log
pleuston_1_3ef9f14874d6 | INFO: Accepting connections at http://0.0.0.0:3000
```
The other components boot without issue.

Docker exec-ing in to the Pleuston container and looking at /config/ocean.js:
```
module.exports = {
    // -----
    // Setup with local services
    // -----
    keeperScheme: 'http',
    keeperHost: 'keeper-contracts',
    keeperPort: 8545,

    aquariusScheme: '',
    aquariusHost: '',
    aquariusPort: 
}
```

This is not the full file as in the repo.

MacOS 10.14.1, Docker 18.09, Docker-Compose 1.23.1

**Comment by kremalicious** [comment]
Guess this was introduced with https://github.com/oceanprotocol/pleuston/pull/169

**Comment by kremalicious** [comment]
those `env` variables are never set in the main docker-compose.yml file in `docker-images`, no mention of anything related to aquarius in there:

https://github.com/oceanprotocol/docker-images/blob/develop/docker-compose.yml#L65

```yaml
  pleuston:
    image: oceanprotocol/pleuston:${OCEAN_VERSION:-stable}
    ports:
    - 3000:3000
    depends_on:
    - keeper-contracts
    environment:
      KEEPER_HOST: keeper-contracts
      OCEAN_HOST: aquarius
      LOCAL_CONTRACTS: 'true'
    volumes:
    - ${ARTIFACTS_FOLDER}:/pleuston/node_modules/@oceanprotocol/keeper-contracts/artifacts/:ro
```

Also not in the `.env` file: https://github.com/oceanprotocol/docker-images/blob/develop/.env. 

So logically, those values are simply empty then, as reported in this issue.
